### ISSUE TITLE
Name change?

### ISSUE THREAD

**Issue by STRML** [STRML/react-router-page-transition#8]
@andreypopp This is a useful enough module that a few people have asked for an "official" version, so I've recently changed the project to export something that can be used via npm.

Before publishing to npm, I think the name should be changed to avoid confusion with `react-router`. What do you think of `rrc-animated-locations`?

**Comment by andreypopp** [comment]
@STRML sorry for late reply. I can transfer repo to you if you want?

**Comment by STRML** [comment]
No problem, this is low priority. If you like - I'll republish then under a new name.

**Comment by andreypopp** [comment]
It says that:
```
STRML/react-router-page-transition already exists
```

**Comment by STRML** [comment]
Had a fork open, try again - thanks

**Comment by andreypopp** [comment]
Done.

**Comment by STRML** [comment]
Thanks.

**Comment by STRML** [comment]
Published as `react-router-component-transition@0.1.0`.
